### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by DaRealMonika** [osp54/Lumus#1]
i can't download the mod by the mod menu and trying to import the mod downloaded by github actions give this error
![Mindustry_2023-03-30-19-18-15](https://user-images.githubusercontent.com/39466656/228986533-a1319f52-20de-469d-b3cc-9dd08415c073.jpg)
btw I'm on mobile

**Comment by osp54** [comment]
> i can't download the mod by the mod menu and trying to import the mod downloaded by github actions give this error ![Mindustry_2023-03-30-19-18-15](https://user-images.githubusercontent.com/39466656/228986533-a1319f52-20de-469d-b3cc-9dd08415c073.jpg) btw I'm on mobile

Sorry, but this mod is in development, and nothing is almost ready yet.
